# Generated by Django 3.0.8 on 2020-07-17 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='approveby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approveby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interface',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interface',
            name='assignon',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updateby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interface',
            name='updatedon',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
