# Generated by Django 3.0.7 on 2020-07-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='updatedon',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
