# Generated by Django 3.0.7 on 2020-07-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
