# Generated by Django 3.0.7 on 2020-07-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_interfacedetail_interface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacedetail',
            old_name='description_is',
            new_name='description',
        ),
    ]
