# Generated by Django 3.0.7 on 2020-07-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_auto_20200730_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacedetail',
            old_name='comment',
            new_name='comments',
        ),
    ]
