# Generated by Django 3.0.7 on 2020-08-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_auto_20200730_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='approveby',
            new_name='approve_by',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='approveon',
            new_name='approve_on',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='createdby',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='createdon',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='publisherschema',
            new_name='publisher_schema',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='subscriberschema',
            new_name='subscriber_schema',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='updatedby',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='updatedon',
            new_name='updated_on',
        ),
    ]
