# Generated by Django 3.0.7 on 2020-08-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_auto_20200804_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='assignon',
            new_name='assign_on',
        ),
    ]
