# Generated by Django 3.0.7 on 2020-08-09 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_1', '0016_auto_20200804_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=50)),
                ('column_name', models.CharField(max_length=50)),
                ('field_type', models.CharField(max_length=50)),
                ('field_length', models.CharField(max_length=50)),
                ('properties', models.CharField(max_length=50)),
                ('default_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterfacefieldDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_table', models.CharField(max_length=50)),
                ('pub_column', models.CharField(max_length=50)),
                ('pub_field_type', models.CharField(max_length=50)),
                ('pub_field_length', models.CharField(max_length=50)),
                ('pub_column_seq', models.IntegerField()),
                ('pub_properties', models.CharField(max_length=50)),
                ('pub_default_value', models.CharField(max_length=100)),
                ('pub_min_occurs', models.IntegerField()),
                ('pub_max_occurs', models.IntegerField()),
                ('sub_table', models.CharField(max_length=50)),
                ('sub_column', models.CharField(max_length=50)),
                ('sub_field_type', models.CharField(max_length=50)),
                ('sub_field_length', models.CharField(max_length=50)),
                ('sub_column_seq', models.IntegerField()),
                ('sub_properties', models.CharField(max_length=50)),
                ('sub_default_value', models.CharField(max_length=50)),
                ('sub_min_occurs', models.IntegerField()),
                ('sub_max_occurs', models.IntegerField()),
                ('Conversion_rule', models.CharField(max_length=250)),
                ('Comments', models.CharField(max_length=250)),
                ('Created_on', models.DateField(blank=True, null=True)),
                ('Updated_on', models.DateField(blank=True, null=True)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.InterfaceDetail')),
            ],
        ),
    ]
