# Generated by Django 3.0.7 on 2020-08-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_interfacefielddetail_schematable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='pub_column_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='pub_default_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='pub_max_occurs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='pub_min_occurs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='sub_column_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='sub_default_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='sub_max_occurs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='sub_min_occurs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
