# Generated by Django 3.0.7 on 2020-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_auto_20200809_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='Comments',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='pub_default_value',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='sub_default_value',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
