# Generated by Django 3.0.7 on 2020-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0019_auto_20200820_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='pub_default_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interfacefielddetail',
            name='sub_default_value',
            field=models.CharField(max_length=50),
        ),
    ]
