# Generated by Django 3.0.7 on 2020-08-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0020_auto_20200820_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfacedetail',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfacedetail',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
