# Generated by Django 3.0.7 on 2020-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0021_auto_20200820_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schematable',
            name='default_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schematable',
            name='field_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schematable',
            name='field_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schematable',
            name='properties',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
